# Generated by Django 2.2.3 on 2019-11-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_remove_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
