# Generated by Django 2.2.3 on 2019-11-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20191126_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.FloatField(choices=[(5, '외투'), (4, '상의'), (3, '하의'), (2, '신발'), (1, '모자')], default=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
